options:
  lineNumbers: true
  spellcheck: true
  askImageFilename: true
  overwriteImages: false
  imagePath: /uploads
  imagePrefix: ''
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: true
